### ISSUE TITLE
Does not support :export

### ISSUE THREAD

**Issue by pietrofxq** [pascalduez/stylelint-config-css-modules#3]
Is it possible to add support for :export when using css lint? Let's say I have this code:

```
:export {
  black: var(--black);
}
```

this throws the error:  Unexpected unknown property "black"   property-no-unknown

**Comment by pietrofxq** [comment]
Fixed by configuring `ignoreProperties ` of `property-no-unknown` in the .stylelintrc

**Comment by natatat** [comment]
@pietrofxq can you show how you're using `ignoreProperties` in your `.stylelintrc` file? I'm running into the same issue and am having trouble finding an example of how to whitelist this correctly.

**Comment by pascalduez** [comment]
@natatat You have a couple of solutions available:

1. Inline comments
```css
:export {
  /* stylelint-disable property-no-unknown */
  black: #000;
  white: #111;
  /* stylelint-enable */
}
```

2. Prefixed names
```css
:export {
  $black: #000;
  $white: #111;
}
```

3. Config whitelist

```json
{
  "rules": {
    "property-no-unknown": [true, {
      "ignoreProperties": ["black", "white"]
    }]
  }
}
```
4. Custom prefix
```css
:export {
  foo-black: #000;
  foo-white: #111;
}
```
```json
{
  "rules": {
    "property-no-unknown": [true, {
      "ignoreProperties": ["/^foo/"]
    }]
  }
}
```
